const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("desktopBridge", {
  getCapabilities: () => ipcRenderer.invoke("desktop:get-capabilities"),
  getNetworkSummary: () => ipcRenderer.invoke("desktop:get-network-summary"),
  registerShortcut: (shortcut) => ipcRenderer.invoke("desktop:register-shortcut", shortcut),
  setTriggerConfig: (value) => ipcRenderer.invoke("desktop:set-trigger-config", value),
  setVoiceRecording: (recording) => ipcRenderer.invoke("desktop:set-voice-recording", Boolean(recording)),
  setVoiceState: (value) => ipcRenderer.invoke("desktop:set-voice-state", value),
  writeClipboard: (text) => ipcRenderer.invoke("desktop:clipboard-write", text),
  pasteActiveWindow: (text) => ipcRenderer.invoke("desktop:paste-active-window", text),
  keyDiagnostic: (event) => ipcRenderer.invoke("desktop:key-diagnostic", event),
  getBailianStatus: () => ipcRenderer.invoke("bailian:get-status"),
  saveBailianCredentials: (value) => ipcRenderer.invoke("bailian:save-credentials", value),
  clearBailianCredentials: () => ipcRenderer.invoke("bailian:clear-credentials"),
  transcribeBailian: (value) => ipcRenderer.invoke("bailian:transcribe", value),
  cancelBailian: (requestId) => ipcRenderer.invoke("bailian:cancel", requestId),
  organizeBailian: (value) => ipcRenderer.invoke("bailian:organize", value),
  cancelBailianOrganizer: (requestId) => ipcRenderer.invoke("bailian:cancel-organize", requestId),
  startBailianRealtime: () => ipcRenderer.invoke("bailian:realtime-start"),
  appendBailianRealtime: (value) => ipcRenderer.invoke("bailian:realtime-append", value),
  finishBailianRealtime: (sessionId) => ipcRenderer.invoke("bailian:realtime-finish", sessionId),
  cancelBailianRealtime: (sessionId) => ipcRenderer.invoke("bailian:realtime-cancel", sessionId),
  onBailianRealtimeEvent: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("bailian-realtime-event", handler); return () => ipcRenderer.removeListener("bailian-realtime-event", handler); },
  onVoiceToggle: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("voice-toggle", handler); return () => ipcRenderer.removeListener("voice-toggle", handler); },
  onVoiceCancel: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("voice-cancel", handler); return () => ipcRenderer.removeListener("voice-cancel", handler); },
  onKeyDiagnostic: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("key-diagnostic", handler); return () => ipcRenderer.removeListener("key-diagnostic", handler); },
  onInputBridgeStatus: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("input-bridge-status", handler); return () => ipcRenderer.removeListener("input-bridge-status", handler); },
  onNavigate: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("desktop-navigate", handler); return () => ipcRenderer.removeListener("desktop-navigate", handler); },
});
