export const AI_STATUS_VERSION = 1;
export const AI_STATES = ["offline", "idle", "listening", "thinking", "working", "waiting", "completed", "error"];
export const AI_PROVIDERS = ["codex", "claude-code", "hermes", "workbody"];
export function validateAiEvent(event) { if (!event || event.version !== AI_STATUS_VERSION || !AI_PROVIDERS.includes(event.provider) || !AI_STATES.includes(event.state) || typeof event.sessionId !== "string" || !event.sessionId || !Number.isInteger(event.sequence) || event.sequence < 0 || Number.isNaN(Date.parse(event.time))) throw new Error("AI 状态事件格式无效"); if (event.progress !== undefined && (!Number.isFinite(event.progress) || event.progress < 0 || event.progress > 100)) throw new Error("AI 状态进度无效"); return Object.freeze({ ...event }); }
export function createAiEvent(provider, state, options = {}) { return validateAiEvent({ version: AI_STATUS_VERSION, provider, state, sessionId: options.sessionId || `mock-${provider}`, activity: String(options.activity || state), progress: options.progress, time: options.time || new Date().toISOString(), sequence: Number.isInteger(options.sequence) ? options.sequence : 0 }); }
export const initialAiState = { events: {}, activeProvider: null, activeSessionId: null, lastEvent: null };
export function reduceAiState(current = initialAiState, candidate) { let event; try { event = validateAiEvent(candidate); } catch { return current; } const previous = current.events[event.provider]; if (previous && previous.sessionId === event.sessionId && event.sequence <= previous.sequence) return current; const nextEvents = { ...current.events, [event.provider]: event }; const active = current.activeProvider && event.provider !== current.activeProvider && event.state !== "offline" ? current.activeProvider : event.provider; return { events: nextEvents, activeProvider: active, activeSessionId: nextEvents[active]?.sessionId || event.sessionId, lastEvent: event }; }
export function disconnectAiProvider(current, provider, time = new Date().toISOString()) { return reduceAiState(current, createAiEvent(provider, "offline", { sessionId: current.events[provider]?.sessionId || `mock-${provider}`, sequence: (current.events[provider]?.sequence || 0) + 1, time, activity: "provider disconnected" })); }
export function legacyState(value) { return value === "waiting_user" ? "waiting" : value === "working" ? "working" : AI_STATES.includes(value) ? value : "idle"; }
