export const LAN_AUDIO_STATES = ["unavailable", "discovering", "connecting", "streaming", "reconnecting", "error", "closed"];
export const AUDIO_FRAME_FORMATS = ["pcm_s16le", "pcm_f32le"];

function bytesOf(data) { return data instanceof ArrayBuffer ? data.byteLength : ArrayBuffer.isView(data) ? data.byteLength : 0; }

export class EasyInputLanAudioAdapter {
  constructor({ transportFactory = null, maxQueueFrames = 32, maxFrameBytes = 256 * 1024, maxSessionBytes = 32 * 1024 * 1024, maxReconnectAttempts = 3, reconnectBaseMs = 100, scheduler = globalThis } = {}) {
    this.transportFactory = transportFactory; this.maxQueueFrames = maxQueueFrames; this.maxFrameBytes = maxFrameBytes; this.maxSessionBytes = maxSessionBytes; this.maxReconnectAttempts = maxReconnectAttempts; this.reconnectBaseMs = reconnectBaseMs; this.scheduler = scheduler; this.listeners = new Set(); this.queue = []; this.seen = new Set(); this.state = "unavailable"; this.transport = null; this.transportUnsubscribe = null; this.streamAbortCleanup = null; this.reconnectTimer = null; this.candidate = null; this.sessionBytes = 0; this.lastSequence = null; this.diagnostics = this.emptyDiagnostics();
  }
  emptyDiagnostics() { return { state: this.state, framesReceived: 0, framesQueued: 0, framesDropped: 0, duplicates: 0, outOfOrder: 0, lateFrames: 0, missingFrames: 0, bytesReceived: 0, queueDepth: 0, reconnectAttempts: 0, lastSequence: null, sampleRate: null, channels: null, format: null, reason: "protocol-unconfirmed" }; }
  setState(state, reason = "") { this.state = state; this.diagnostics.state = state; if (reason) this.diagnostics.reason = reason; this.emit({ type: "state", state, reason }); }
  emit(event) { this.listeners.forEach((listener) => listener(event)); }
  subscribe(listener) { this.listeners.add(listener); return () => this.listeners.delete(listener); }
  async discover(options = {}) { this.setState("discovering"); if (!this.transportFactory?.discover) { this.setState("unavailable", "protocol-unconfirmed"); return { state: this.state, candidates: [], reason: "protocol-unconfirmed" }; } try { const candidates = await this.transportFactory.discover(options); return { state: this.state, candidates: Array.isArray(candidates) ? candidates.map((item) => ({ id: String(item.id || "candidate"), kind: String(item.kind || "unknown") })) : [] }; } catch (error) { this.setState("error", "discovery-failed"); return { state: this.state, candidates: [], reason: "discovery-failed" }; } }
  async getStatus() { return { connected: this.state === "streaming", available: Boolean(this.transportFactory), state: this.state, reason: this.diagnostics.reason }; }
  async openStream(options = {}) { const result = await this.startStream(options); if (!result.ok) throw new Error("EasyInput 局域网音频协议尚未确认"); return result; }
  async connect(candidate, options = {}) { await this.stop("reconnect"); this.candidate = candidate || null; if (!this.transportFactory?.connect) { this.setState("unavailable", "protocol-unconfirmed"); return { ok: false, state: this.state, reason: "protocol-unconfirmed" }; } this.setState("connecting"); try { this.transport = await this.transportFactory.connect(candidate, options); this.attachTransport(); return { ok: true, state: this.state }; } catch (error) { this.setState("error", "connect-failed"); return { ok: false, state: this.state, reason: "connect-failed" }; } }
  attachTransport() { if (!this.transport) return; const onFrame = (frame) => this.ingestFrame(frame); const onDisconnect = () => this.handleDisconnect(); if (this.transport.subscribe) this.transportUnsubscribe = this.transport.subscribe({ onFrame, onDisconnect }); else { this.transport.onFrame = onFrame; this.transport.onDisconnect = onDisconnect; } }
  async startStream(options = {}) { if (!this.transport) { this.setState("unavailable", "protocol-unconfirmed"); return { ok: false, state: this.state }; } if (options.signal?.aborted) { await this.stop("cancelled"); return { ok: false, state: this.state, reason: "cancelled" }; } this.streamAbortCleanup?.(); const cancel = () => { void this.stop("cancelled"); }; options.signal?.addEventListener("abort", cancel, { once: true }); this.streamAbortCleanup = () => options.signal?.removeEventListener("abort", cancel); try { await this.transport.startStream?.(options); if (options.signal?.aborted) { await this.stop("cancelled"); return { ok: false, state: this.state, reason: "cancelled" }; } this.setState("streaming"); return { ok: true, state: this.state }; } catch { this.streamAbortCleanup?.(); this.streamAbortCleanup = null; this.setState("error", "stream-start-failed"); return { ok: false, state: this.state, reason: "stream-start-failed" }; } }
  validateFrame(frame) { if (!frame || !Number.isInteger(frame.sequence) || frame.sequence < 0) return "invalid-sequence"; if (!AUDIO_FRAME_FORMATS.includes(frame.format)) return "unsupported-format"; if (!Number.isInteger(frame.sampleRate) || frame.sampleRate < 8000 || frame.sampleRate > 192000) return "invalid-sample-rate"; if (!Number.isInteger(frame.channels) || frame.channels < 1 || frame.channels > 2) return "invalid-channels"; const size = bytesOf(frame.data); if (!size || size > this.maxFrameBytes) return "frame-too-large-or-empty"; if (this.sessionBytes + size > this.maxSessionBytes) return "session-size-limit"; return null; }
  ingestFrame(frame) { const reason = this.validateFrame(frame); if (reason) { this.diagnostics.framesDropped += 1; this.diagnostics.reason = reason; this.emit({ type: "frame-rejected", reason }); return false; } if (this.seen.has(frame.sequence)) { this.diagnostics.duplicates += 1; this.diagnostics.framesDropped += 1; return false; } if (this.lastSequence !== null) { if (frame.sequence < this.lastSequence) { this.diagnostics.outOfOrder += 1; this.diagnostics.lateFrames += 1; this.diagnostics.framesDropped += 1; return false; } if (frame.sequence > this.lastSequence + 1) this.diagnostics.missingFrames += frame.sequence - this.lastSequence - 1; } this.seen.add(frame.sequence); this.lastSequence = frame.sequence; const size = bytesOf(frame.data); this.sessionBytes += size; this.diagnostics.framesReceived += 1; this.diagnostics.bytesReceived += size; this.diagnostics.sampleRate = frame.sampleRate; this.diagnostics.channels = frame.channels; this.diagnostics.format = frame.format; if (this.queue.length >= this.maxQueueFrames) { this.queue.shift(); this.diagnostics.framesDropped += 1; } this.queue.push({ sequence: frame.sequence, sampleRate: frame.sampleRate, channels: frame.channels, format: frame.format, data: frame.data }); this.diagnostics.framesQueued = this.queue.length; this.diagnostics.queueDepth = this.queue.length; this.emit({ type: "audio", chunk: this.queue.at(-1) }); return true; }
  readChunk() { const chunk = this.queue.shift() || null; this.diagnostics.queueDepth = this.queue.length; return chunk; }
  handleDisconnect() { if (this.state === "closed" || this.state === "unavailable") return; if (this.diagnostics.reconnectAttempts >= this.maxReconnectAttempts) { this.setState("error", "reconnect-limit"); return; } this.setState("reconnecting", "transport-disconnected"); const attempt = ++this.diagnostics.reconnectAttempts; const delay = this.reconnectBaseMs * (2 ** (attempt - 1)); this.reconnectTimer = this.scheduler.setTimeout(async () => { this.reconnectTimer = null; const connected = await this.connect(this.candidate); if (connected.ok) await this.startStream(); else this.handleDisconnect(); }, delay); }
  async stop(reason = "closed") { if (this.reconnectTimer) { this.scheduler.clearTimeout(this.reconnectTimer); this.reconnectTimer = null; } this.streamAbortCleanup?.(); this.streamAbortCleanup = null; try { await this.transport?.stopStream?.(reason); } catch { /* release still continues */ } this.transportUnsubscribe?.(); this.transportUnsubscribe = null; this.transport = null; this.queue = []; this.seen.clear(); this.sessionBytes = 0; this.diagnostics.queueDepth = 0; if (reason === "cancelled") this.setState("closed", "cancelled"); else this.setState("closed", reason); return { ok: true, state: this.state }; }
  getDiagnostics() { const { state, framesReceived, framesQueued, framesDropped, duplicates, outOfOrder, lateFrames, missingFrames, bytesReceived, queueDepth, reconnectAttempts, lastSequence, sampleRate, channels, format, reason } = this.diagnostics; return { state, framesReceived, framesQueued, framesDropped, duplicates, outOfOrder, lateFrames, missingFrames, bytesReceived, queueDepth, reconnectAttempts, lastSequence, sampleRate, channels, format, reason }; }
}
